### ISSUE TITLE
Warning supression

### ISSUE THREAD

**Issue by karelz** [terrajobst/pns-scan#2]
We should allow developers to customize he warnings.

Ability to:
* Disable warnings for method / type / assembly
* Disable warnings for specific platform (Mac, iOS, Android, Xamarin)
* Disable only PNSE / Obsolete warnings

I would recommend an option to have configuration in a config file (xml/json), which can be shared/copied between projects.
Allowing multiple configs may be even better (project-wide / team-wide + project-specific).

**Comment by terrajobst** [comment]
That's already supported and works as follows:

1. Current call site

![image](https://cloud.githubusercontent.com/assets/5169960/24517608/d5c6682e-1533-11e7-8332-ae5a82a00251.png)

2. Project scope

![image](https://cloud.githubusercontent.com/assets/5169960/24517680/f81f0f20-1533-11e7-98df-36dfaadd5f54.png)

3. Arbitrary scope

Put the suppression from (2) in specific file and between projects as needed.

**Comment by karelz** [comment]
Lovely ... now you have proof I didn't even try it, just looked at your screenshot ;-)
